{
  "openapi": "3.0.0",
  "info": {
    "title": "abyssal",
    "version": "0.1.0"
  },
  "paths": {
    "/info": {
      "get": {
        "operationId": "get_info",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetInfoResponse"
                }
              }
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "tags": [
          "Users"
        ],
        "operationId": "login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "500": {
            "description": "[500 Internal Server Error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)",
            "content": {
              "ErrorMeta": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMeta"
                },
                "example": {
                  "status": 500,
                  "code": "error.example",
                  "message": "An example error occurred: <reason>",
                  "explanation": "The example error is raised when..."
                }
              }
            }
          },
          "401": {
            "description": "[401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)",
            "content": {
              "ErrorMeta": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMeta"
                },
                "example": {
                  "status": 401,
                  "code": "error.example",
                  "message": "An example error occurred: <reason>",
                  "explanation": "The example error is raised when..."
                }
              }
            }
          }
        }
      }
    },
    "/users/logout": {
      "post": {
        "tags": [
          "Users"
        ],
        "operationId": "logout",
        "responses": {
          "200": {
            "description": ""
          },
          "500": {
            "description": "[500 Internal Server Error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)",
            "content": {
              "ErrorMeta": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMeta"
                },
                "example": {
                  "status": 500,
                  "code": "error.example",
                  "message": "An example error occurred: <reason>",
                  "explanation": "The example error is raised when..."
                }
              }
            }
          },
          "401": {
            "description": "[401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)",
            "content": {
              "ErrorMeta": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMeta"
                },
                "example": {
                  "status": 401,
                  "code": "error.example",
                  "message": "An example error occurred: <reason>",
                  "explanation": "The example error is raised when..."
                }
              }
            }
          }
        },
        "security": [
          {
            "HttpAuth": []
          }
        ]
      }
    },
    "/users/self": {
      "get": {
        "tags": [
          "Users"
        ],
        "operationId": "get_user_self",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GenericUser"
                }
              }
            }
          },
          "500": {
            "description": "[500 Internal Server Error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)",
            "content": {
              "ErrorMeta": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMeta"
                },
                "example": {
                  "status": 500,
                  "code": "error.example",
                  "message": "An example error occurred: <reason>",
                  "explanation": "The example error is raised when..."
                }
              }
            }
          },
          "401": {
            "description": "[401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)",
            "content": {
              "ErrorMeta": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMeta"
                },
                "example": {
                  "status": 401,
                  "code": "error.example",
                  "message": "An example error occurred: <reason>",
                  "explanation": "The example error is raised when..."
                }
              }
            }
          }
        },
        "security": [
          {
            "HttpAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "GetInfoResponse": {
        "type": "object",
        "required": [
          "version"
        ],
        "properties": {
          "version": {
            "type": "string"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "required": [
          "token",
          "user"
        ],
        "properties": {
          "token": {
            "$ref": "#/components/schemas/Uuid"
          },
          "user": {
            "$ref": "#/components/schemas/GenericUser"
          }
        }
      },
      "Uuid": {
        "type": "string"
      },
      "GenericUser": {
        "type": "object",
        "required": [
          "groups",
          "id",
          "kind",
          "name",
          "permissions"
        ],
        "properties": {
          "id": {
            "$ref": "#/components/schemas/Uuid"
          },
          "kind": {
            "$ref": "#/components/schemas/UserKind"
          },
          "name": {
            "type": "string"
          },
          "groups": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "permissions": {
            "$ref": "#/components/schemas/Array_of_Permission"
          }
        }
      },
      "UserKind": {
        "type": "string",
        "enum": [
          "local",
          "oidc",
          "application"
        ]
      },
      "Array_of_Permission": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Permission"
        }
      },
      "Permission": {
        "oneOf": [
          {
            "description": "Supersedes all other permissions Also is *required* to allow access to: - OIDC management - User/group management - Permission assignment",
            "type": "object",
            "required": [
              "permission"
            ],
            "properties": {
              "permission": {
                "type": "string",
                "enum": [
                  "administrator"
                ]
              }
            }
          },
          {
            "description": "Invite management",
            "type": "object",
            "required": [
              "administrate",
              "capability",
              "permission",
              "root"
            ],
            "properties": {
              "permission": {
                "type": "string",
                "enum": [
                  "invites"
                ]
              },
              "root": {
                "description": "Root allowed to create invites to",
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Uuid"
                  }
                ]
              },
              "capability": {
                "description": "What level of access to grant",
                "allOf": [
                  {
                    "$ref": "#/components/schemas/PermissionCapability"
                  }
                ]
              },
              "administrate": {
                "description": "Whether to allow access to invites owned by other users",
                "type": "boolean"
              }
            }
          },
          {
            "description": "Upload dropbox management",
            "type": "object",
            "required": [
              "administrate",
              "capability",
              "permission",
              "root"
            ],
            "properties": {
              "permission": {
                "type": "string",
                "enum": [
                  "upload_targets"
                ]
              },
              "root": {
                "description": "Roots allowed to create upload targets for",
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Uuid"
                  }
                ]
              },
              "capability": {
                "description": "What level of access to grant",
                "allOf": [
                  {
                    "$ref": "#/components/schemas/PermissionCapability"
                  }
                ]
              },
              "administrate": {
                "description": "Whether to allow access to upload targets owned by other users",
                "type": "boolean"
              }
            }
          },
          {
            "description": "Access to a root directory",
            "type": "object",
            "required": [
              "capability",
              "permission",
              "root",
              "top_level"
            ],
            "properties": {
              "permission": {
                "type": "string",
                "enum": [
                  "root_directory"
                ]
              },
              "root": {
                "description": "Root ID",
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Uuid"
                  }
                ]
              },
              "top_level": {
                "description": "Top-level directory",
                "allOf": [
                  {
                    "$ref": "#/components/schemas/RootTopLevel"
                  }
                ]
              },
              "capability": {
                "description": "What level of access to grant",
                "allOf": [
                  {
                    "$ref": "#/components/schemas/PermissionCapability"
                  }
                ]
              }
            }
          }
        ]
      },
      "PermissionCapability": {
        "oneOf": [
          {
            "description": "View existing <resource>",
            "type": "string",
            "enum": [
              "read"
            ]
          },
          {
            "description": "Edit existing <resource>",
            "type": "string",
            "enum": [
              "edit"
            ]
          },
          {
            "description": "Create/destroy existing <resource>",
            "type": "string",
            "enum": [
              "manage"
            ]
          }
        ]
      },
      "RootTopLevel": {
        "oneOf": [
          {
            "type": "object",
            "required": [
              "kind"
            ],
            "properties": {
              "kind": {
                "type": "string",
                "enum": [
                  "root"
                ]
              }
            }
          },
          {
            "type": "object",
            "required": [
              "kind",
              "parent"
            ],
            "properties": {
              "kind": {
                "type": "string",
                "enum": [
                  "home"
                ]
              },
              "parent": {
                "type": "string"
              }
            }
          },
          {
            "type": "object",
            "required": [
              "kind",
              "path"
            ],
            "properties": {
              "kind": {
                "type": "string",
                "enum": [
                  "directory"
                ]
              },
              "path": {
                "type": "string"
              }
            }
          }
        ]
      },
      "ErrorMeta": {
        "type": "object",
        "required": [
          "code",
          "explanation",
          "message",
          "status"
        ],
        "properties": {
          "status": {
            "type": "integer",
            "format": "uint16",
            "minimum": 0.0
          },
          "code": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "explanation": {
            "type": "string"
          }
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": [
          "password",
          "username"
        ],
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "HttpAuth": {
        "description": "Authorization header containing either `Token <session token>` or `Application <client_id>:<client_secret>",
        "type": "http",
        "scheme": "Token | Application",
        "bearerFormat": "Token | Application"
      }
    }
  }
}